// This file is automatically generated during build
export const BUILD_INFO = {
	version: '0.0.0',
	namespace: 'ng-pwa-app',
	libVersion: 'unknown',
	libName: 'unknown',
	commit: '509c5dd7cf92c7230d4c3e03503797ebbe3cf1cb',
	branch: 'main',
	lastCommitMessage: 'Remove unnecessary permissions from workflow configuration',
	lastCommitAuthor: 'mahindar5',
	lastCommitDate: '2025-03-30 23:39:27 -0700',
	buildNumber: '1743815459214',
	buildId: 'build-1743815459214',
	buildUrl: '',
	buildEnvironment: 'development',
	buildHost: 'DESKTOP-NUHLUK',
	buildTarget: 'development',
	nodeVersion: 'v22.13.1',
	npmVersion: '10.9.2',
	os: 'win32',
	arch: 'x64',
	timestamp: '2025-04-05T01:10:59.190Z',
	buildDate: '2025-04-04',
	buildTime: '6:10:59 p.m.',
	dependencies: {
		angular: '19.0.0',
		typescript: '~5.6.2',
		rxjs: '~7.8.0',
		materialUI: 'unknown'
	}
};
