name: build-deploy-pages

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: write
  id-token: write
  pages: write
  packages: read

jobs:
  deploy-app:
    uses: ./.github/workflows/common-build-deploy-pages.yml
    with:
      base-href: "/ng-pwa-app/"
      npm-packages: "@mahindar5/common-lib@latest"
