name: reusable-deploy-app

on:
  workflow_call:
    inputs:
      base-href:
        required: true
        type: string
      npm-packages:
        required: true
        type: string

permissions:
  contents: write
  id-token: write
  pages: write
  packages: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@main

      - name: Set up Node.js
        uses: actions/setup-node@main
        with:
          node-version: "lts/*"
          cache: "npm"

      - name: Configure npm for installing packages
        run: |
          echo "@mahindar5:registry=https://npm.pkg.github.com" >> ~/.npmrc
          echo "//npm.pkg.github.com/:_authToken=${{ secrets.GITHUB_TOKEN }}" >> ~/.npmrc
          echo "registry=https://registry.npmjs.org/" >> ~/.npmrc

      - name: Install dependencies
        run: npm ci && npm install ${{ inputs.npm-packages }}

      - name: Build application
        run: npm run build -- --output-path=dist --base-href=${{ inputs.base-href }}

      - name: Copy docs/index.html to docs/404.html
        run: cp docs/index.html docs/404.html

      - name: Copy stats.json to repo root
        run: |
          mkdir -p stats
          DATE=$(date +'%Y%m%d')
          cp dist/stats.json stats/${DATE}.json

      - name: Commit stats file
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          DATE=$(date +'%Y%m%d')
          git add stats/${DATE}.json
          git commit -m "Update ${DATE}.json [skip ci]" || echo "No changes to commit"
          git push

      - name: Archive production artifacts
        uses: actions/upload-pages-artifact@main
        with:
          path: dist/browser

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@main
