# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and deploy to GitHub Pages
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: ng-pwa-app-deploy

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: write # This is necessary to checkout the repository and write the artifacts
  id-token: write # This is necessary to deploy to GitHub Pages
  pages: write # This is necessary to deploy to GitHub Pages
  packages: read # This is necessary to install dependencies from GitHub Packages

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@main
      - name: Set up Node.js
        uses: actions/setup-node@main
        with:
          node-version: "lts/*"
          cache: "npm"
      - name: Configure npm for publishing
        run: |
          echo "@mahindar5:registry=https://npm.pkg.github.com" >> ~/.npmrc
          echo "//npm.pkg.github.com/:_authToken=${{ secrets.GITHUB_TOKEN }}" >> ~/.npmrc
          echo "registry=https://registry.npmjs.org/" >> ~/.npmrc
      - run: npm ci && npm install @mahindar5/common-lib@latest
      - run: npm run build -- --output-path=dist --base-href=/ng-pwa-app/

      - name: Copy stats.json to repo root
        run: |
          mkdir -p stats
          cp dist/stats.json stats/${{ github.run_number }}.json

      - name: Commit stats/buildnumber.json
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add stats/${{ github.run_number }}.json
          git commit -m 'Add ${{ github.run_number }}.json [skip ci]'
          git push
      - name: Archive production artifacts
        uses: actions/upload-pages-artifact@main
        with:
          path: dist/browser

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@main
