name: ng-pwa-app-deploy

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: write
  id-token: write
  pages: write
  packages: read

jobs:
  deploy-app:
    uses: mahindar5/common-lib/.github/workflows/common-deploy-app.yml@main
    with:
      base-href: "/ng-pwa-app/"
      npm-packages: "@mahindar5/common-lib@latest"
