# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and deploy to GitHub Pages
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: ng-pwa-app-deploy

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@main
      - name: Set up Node.js
        uses: actions/setup-node@main
        with:
          node-version: "lts/*"
          cache: "npm"
      - run: npm ci
      - run: npm run build -- --output-path=dist --base-href=/ng-pwa-app/

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: dist/ng-pwa-app
          branch: gh-pages
          token: ${{ secrets.GITHUB_TOKEN }}
